// <auto-generated />
using System;
using HealthRecord.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthRecord.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325101540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HealthRecord.API.Models.Entities.BloodPressureDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementPosition")
                        .HasColumnType("longtext");

                    b.Property<int?>("NhiImportLogId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("Pulse")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("NhiImportLogId");

                    b.HasIndex("UserId");

                    b.ToTable("BloodPressureDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.EmergencyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClinicDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Copay")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hospital")
                        .HasColumnType("longtext");

                    b.Property<string>("HospitalCode")
                        .HasColumnType("longtext");

                    b.Property<int?>("NhiImportLogId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryDiagnosis")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryIcdCode")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondaryDiagnoses")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VisitSeq")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NhiImportLogId");

                    b.HasIndex("UserId");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.LabResultDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbnormal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNumeric")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NhiCode")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("NhiImportLogId")
                        .HasColumnType("int");

                    b.Property<string>("NhiItemName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NhiRawRange")
                        .HasColumnType("longtext");

                    b.Property<string>("NhiRawValue")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("NormalMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NormalMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ValueText")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("NhiImportLogId");

                    b.HasIndex("NhiCode", "NhiItemName");

                    b.HasIndex("UserId", "ItemCode");

                    b.ToTable("LabResultDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.MedicationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Days")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DrugType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<string>("NhiDrugCode")
                        .HasColumnType("longtext");

                    b.Property<int?>("NhiImportLogId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("NhiImportLogId");

                    b.HasIndex("UserId");

                    b.ToTable("MedicationDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.NhiImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DateRangeEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateRangeStart")
                        .HasColumnType("date");

                    b.Property<int>("HealthRecordCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LabCount")
                        .HasColumnType("int");

                    b.Property<int>("MedicationCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedLabs")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NhiImportLogs");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BloodType")
                        .HasColumnType("longtext");

                    b.Property<string>("ChronicConditions")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.BloodPressureDetail", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.HealthRecord", "HealthRecord")
                        .WithMany("BloodPressures")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.NhiImportLog", "NhiImportLog")
                        .WithMany()
                        .HasForeignKey("NhiImportLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("BloodPressures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("NhiImportLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.EmergencyContact", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.HealthRecord", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.NhiImportLog", "NhiImportLog")
                        .WithMany()
                        .HasForeignKey("NhiImportLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("HealthRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhiImportLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.LabResultDetail", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.HealthRecord", "HealthRecord")
                        .WithMany("LabResults")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.NhiImportLog", "NhiImportLog")
                        .WithMany()
                        .HasForeignKey("NhiImportLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("LabResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("NhiImportLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.MedicationDetail", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.HealthRecord", "HealthRecord")
                        .WithMany("Medications")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.NhiImportLog", "NhiImportLog")
                        .WithMany()
                        .HasForeignKey("NhiImportLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("Medications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("NhiImportLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.NhiImportLog", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("NhiImportLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.HealthRecord", b =>
                {
                    b.Navigation("BloodPressures");

                    b.Navigation("LabResults");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.User", b =>
                {
                    b.Navigation("BloodPressures");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("HealthRecords");

                    b.Navigation("LabResults");

                    b.Navigation("Medications");

                    b.Navigation("NhiImportLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
