// <auto-generated />
using System;
using HealthRecord.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthRecord.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HealthRecord.API.Models.Entities.BloodPressureDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arm")
                        .HasColumnType("longtext");

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementPosition")
                        .HasColumnType("longtext");

                    b.Property<int?>("Pulse")
                        .HasColumnType("int");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BloodPressureDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.EmergencyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("NhiImportLogId")
                        .HasColumnType("int");

                    b.Property<string>("NhiInstitution")
                        .HasColumnType("longtext");

                    b.Property<string>("NhiInstitutionCode")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("NhiResultDate")
                        .HasColumnType("date");

                    b.Property<string>("NhiVisitSeq")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhiImportLogId")
                        .HasDatabaseName("idx_import_log");

                    b.HasIndex("UserId", "RecordType")
                        .HasDatabaseName("idx_user_type");

                    b.HasIndex("UserId", "RecordedAt")
                        .HasDatabaseName("idx_user_date");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.LabResultDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<bool>("IsNumeric")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NhiOrderName")
                        .HasColumnType("longtext");

                    b.Property<string>("NhiRawValue")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserLabItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ValueText")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId")
                        .HasDatabaseName("idx_lab_record");

                    b.HasIndex("UserId");

                    b.HasIndex("UserLabItemId");

                    b.HasIndex("ItemCode", "ItemName")
                        .HasDatabaseName("idx_lab_item");

                    b.ToTable("LabResultDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.MedicationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Copayment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Dosage")
                        .HasColumnType("longtext");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .HasColumnType("longtext");

                    b.Property<string>("GenericName")
                        .HasColumnType("longtext");

                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NhiDrugCode")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Route")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VisitDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId")
                        .HasDatabaseName("idx_med_record");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitDetailId");

                    b.ToTable("MedicationDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.NhiImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRangeEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRangeStart")
                        .HasColumnType("date");

                    b.Property<int>("DuplicateLabCount")
                        .HasColumnType("int");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LabCount")
                        .HasColumnType("int");

                    b.Property<int>("MedicationCount")
                        .HasColumnType("int");

                    b.Property<int>("NewItemCount")
                        .HasColumnType("int");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedLabCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VisitCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FileHash")
                        .IsUnique()
                        .HasDatabaseName("uq_user_hash");

                    b.ToTable("NhiImportLogs");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.SymptomLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyLocation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("SymptomType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Triggers")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedAt")
                        .HasDatabaseName("idx_symptom_user_date");

                    b.HasIndex("UserId", "SymptomType")
                        .HasDatabaseName("idx_symptom_user_type");

                    b.ToTable("SymptomLogs");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BloodType")
                        .HasColumnType("longtext");

                    b.Property<string>("ChronicConditions")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.UserLabItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("NormalMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NormalMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemCode", "ItemName")
                        .IsUnique()
                        .HasDatabaseName("uq_user_item");

                    b.ToTable("UserLabItems");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.VisitDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CopaymentCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisCode1")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisCode2")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisCode3")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisCode4")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisCode5")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisName1")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisName2")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisName3")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisName4")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisName5")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorName")
                        .HasColumnType("longtext");

                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MedicalCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NhiRawData")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VisitType")
                        .HasColumnType("longtext");

                    b.Property<string>("VisitTypeCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("VisitDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.BloodPressureDetail", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.HealthRecord", "HealthRecord")
                        .WithOne("BloodPressureDetail")
                        .HasForeignKey("HealthRecord.API.Models.Entities.BloodPressureDetail", "HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("BloodPressures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.EmergencyContact", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.HealthRecord", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.NhiImportLog", "NhiImportLog")
                        .WithMany("HealthRecords")
                        .HasForeignKey("NhiImportLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("HealthRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhiImportLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.LabResultDetail", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.HealthRecord", "HealthRecord")
                        .WithMany("LabResults")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("LabResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthRecord.API.Models.Entities.UserLabItem", "UserLabItem")
                        .WithMany("LabResults")
                        .HasForeignKey("UserLabItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HealthRecord");

                    b.Navigation("User");

                    b.Navigation("UserLabItem");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.MedicationDetail", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.HealthRecord", "HealthRecord")
                        .WithMany("Medications")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("Medications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthRecord.API.Models.Entities.VisitDetail", "VisitDetail")
                        .WithMany("Medications")
                        .HasForeignKey("VisitDetailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HealthRecord");

                    b.Navigation("User");

                    b.Navigation("VisitDetail");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.NhiImportLog", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("NhiImportLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.SymptomLog", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("SymptomLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.UserLabItem", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("UserLabItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.VisitDetail", b =>
                {
                    b.HasOne("HealthRecord.API.Models.Entities.HealthRecord", "HealthRecord")
                        .WithOne("VisitDetail")
                        .HasForeignKey("HealthRecord.API.Models.Entities.VisitDetail", "HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthRecord.API.Models.Entities.User", "User")
                        .WithMany("VisitDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.HealthRecord", b =>
                {
                    b.Navigation("BloodPressureDetail");

                    b.Navigation("LabResults");

                    b.Navigation("Medications");

                    b.Navigation("VisitDetail");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.NhiImportLog", b =>
                {
                    b.Navigation("HealthRecords");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.User", b =>
                {
                    b.Navigation("BloodPressures");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("HealthRecords");

                    b.Navigation("LabResults");

                    b.Navigation("Medications");

                    b.Navigation("NhiImportLogs");

                    b.Navigation("SymptomLogs");

                    b.Navigation("UserLabItems");

                    b.Navigation("VisitDetails");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.UserLabItem", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("HealthRecord.API.Models.Entities.VisitDetail", b =>
                {
                    b.Navigation("Medications");
                });
#pragma warning restore 612, 618
        }
    }
}
